name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo add-apt-repository ppa:kelleyk/emacs -y

          sudo apt install emacs28 -y
          sudo apt install git jq mercurial texinfo -y

          echo -e "[ui]\ntls = False" >> $HOME/.hgrc
          echo -e "[extensions]\npurge = " >> $HOME/.hgrc

      - name: Run testcases
        run: |
          emacs --batch --eval "(progn (setq package-check-signature nil) (package-initialize) (add-to-list 'package-archives (cons \"melpa\" \"https://melpa.org/packages/\") t) (package-refresh-contents) (package-install 'projectile) (package-install 'vertico) (package-install 'eglot) (package-install 'fringe-helper))"
          emacs --batch --eval '(let ((default-directory "~/.emacs.d/elpa")) (normal-top-level-add-subdirs-to-load-path))' -l projectile -l org-linenote.el -l org-linenote-test.el -l ert -f ert-run-tests-batch-and-exit;
